version: '3'
services:
  postgres:
    restart: unless-stopped
    image: "postgres"
    environment: 
      - POSTGRES_USER=${POSTGRES_USER:-recipesbot}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-recipesbot}
      - POSTGRES_DB=${POSTGRES_DATABASE:-recipesbot}
    ports:
      - 5432:5432
    volumes:
      - database-data:/var/lib/postgresql/data/
      - ./docker/postgres:/docker-entrypoint-initdb.d/

  recipesbot:
    container_name: recipesbot
    restart: unless-stopped
    depends_on: 
      - postgres
    build: 
        dockerfile: Dockerfile
        context: .
    image: recipesbot
    environment: 
        - AEMET_TOKEN=${AEMET_TOKEN}
        - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
        - TELEGRAM_GROUP_ID=${TELEGRAM_GROUP_ID}
        - CITY_ID=${CITY_ID}
        - POSTGRES_HOST=${POSTGRES_HOST:-postgres}
        - POSTGRES_USER=${POSTGRES_USER:-recipesbot}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-recipesbot}
        - POSTGRES_DATABASE=${POSTGRES_DATABASE:-recipesbot}
        - WEATHER_SCHEDULE=08:00,12:00,15:00,18:00,22:00,00:00
  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - 6001:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-postgres@postgres.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-postgres}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  database-data:
    external: false
  pgadmin-data: